### ISSUE TITLE
Allow customized line length for generated code file

### ISSUE THREAD

**Issue by ludy-auror** [localizely/intl_utils#128]
Hi guys, I am using latest Flutter Intl plugin `1.18.5` for Android Sutdio.

I am wondering if a new configuration option can be added to set the line length (number of characters before line break) for the generated code file like `messages_xx.dart` and `l10n.dart`. 

The reason is that `dart format` allows setting custom line length, and our project is using a more generous 120 characters per line than the default 80. In this case, each time Flutter Intl plugin is invoked, the `messages_xx.dart` and `l10n.dart` files change unnecessarily from 120 per line back to 80 per line.

It would be nice to have a new configuration option can be added to `pubspec.yaml`, so that the generated files have the correct line length, for example:

```yaml
flutter_intl:
  enabled: true
  class_name: S
  line_length: 120 # <-- Propose to add this new config 
```

Hope I am posting to the right repo, as far as I understand, the Flutter Intl plugin invokes `intl_utils` behind the scene.

Thanks in advance
