### ISSUE TITLE
Custom path for generated files

### ISSUE THREAD

**Issue by edTheGuy00** [localizely/intl_utils#3]
I want to be able to place all generated code in a custom directory instead of the default `generated` path, via an option in `pubspec.yaml`

```dart
flutter_intl:
     custom_path: "my_custom_directory"
```

So this would place all the code in `lib/my_custom_directory` instead of `lib/generated` 

I needed this pretty quick, [so I forked this and added support for a custom path option](https://github.com/edTheGuy00/intl_utils/commit/bc9b79dba383f0f42ec1900421856c344f5e0f62) 

I can make a PR, clean up some things, and check for anything I missed if You guys want to add this option.

**Comment by Marek00Malik** [comment]
I think this is already there:
```  
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  **output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated**
```

You need to run the command line tool to get the generated folder in the new directory.
