### ISSUE TITLE
incompatiblity with flutter_driver (flutter 2)?

### ISSUE THREAD

**Issue by christophemacabiau** [localizely/intl_utils#39]
in a fresh app:
```bash
flutter create myapp
```
with this pubspec
```yaml
name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_utils: any

flutter:
  uses-material-design: true
```
I get this error:
```

--

[myapp] flutter pub get
Running "flutter pub get" in myapp...                           
Because every version of flutter_driver from sdk depends on webdriver 2.1.2 which depends on archive >=1.0.0 <3.0.0, every version of flutter_driver from sdk requires archive >=1.0.0 <3.0.0.
And because intl_utils >=2.0.0 depends on archive ^3.0.0, flutter_driver from sdk is incompatible with intl_utils >=2.0.0.


And because intl_utils ^1.9.0 depends on intl_translation 0.17.10+1 and intl_utils >=1.6.3 <1.9.0 depends on intl_translation 0.17.10, if flutter_driver any from sdk and intl_utils >=1.6.3 then intl_translation 0.17.10 or 0.17.10+1.
Because intl_utils <1.2.1 depends on intl_translation 0.17.8 and intl_utils >=1.2.1 <1.6.3 depends on intl_translation 0.17.9, intl_utils <1.6.3 requires intl_translation 0.17.8 or 0.17.9.



Thus, if flutter_driver any from sdk and intl_utils any then intl_translation 0.17.8 or 0.17.9 or 0.17.10 or 0.17.10+1.
And because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0, if flutter_driver any from sdk and intl_utils any then intl >=0.15.3 <0.17.0.
And because myapp depends on flutter_localizations any from sdk which depends on intl 0.17.0, flutter_driver from sdk is incompatible with intl_utils.


So, because myapp depends on both flutter_driver any from sdk and intl_utils any, version solving failed.
pub get failed (1; So, because myapp depends on both flutter_driver any from sdk and intl_utils any, version solving failed.)
exit code 1
```
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.55.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by aleksakrstic** [comment]
Hi @christophemacabiau 
Could you try by changing `environment.sdk` to `>=2.12.0 <3.0.0` so we are sure it uses Flutter 2+?

**Comment by christophemacabiau** [comment]
same problem with 
```yaml
name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_utils: any

flutter:
  uses-material-design: true
```
