### ISSUE TITLE
pubspec configuration option to exclude / include tags

### ISSUE THREAD

**Issue by ToniTornado** [localizely/intl_utils#55]
It would be great if we could specify tags that will not converted to Dart code when downloading updated translations.

```
flutter_intl:
  enabled: false
  exclude_tags: 
    - EmailTemplates 
  // -- or --
  include_tags:
    - SignUp
    - Settings
    - Home Page
    - Gallery
```

I have a handful of keys that belong to the project but are not (yet) needed in the final app like email templates. This way they are not shipped unnecessarily.

**Comment by lzoran** [comment]
Hi @ToniTornado,

The latest version of the `intl_utils` package (`2.4.0`) now supports:
- tagging added/updated/removed string keys during upload on Localizely platform
- downloading tagged string keys from the Localizely platform

**Upload config:**

To add tags to added/updated/removed string keys during upload, you should update the `flutter_intl` section of the `pubspec.yaml` file with the `upload_tag_added`, `upload_tag_updated`, and `upload_tag_removed`.

```
flutter_intl:
  enabled: true
  localizely:
    project_id: <PROJECT_ID>
    upload_tag_added:
      - added
    upload_tag_updated:
      - updated
    upload_tag_removed:
      - removed
```

To pass added/updated/removed tags during the command run, you can use the `upload-tag-added`, `upload-tag-updated`, and `upload-tag-removed` optional args.

```
flutter pub run intl_utils:localizely_upload_main --upload-tag-added=added --upload-tag-updated=updated --upload-tag-removed=removed
```

**Download config:**

To download string keys with specific tags or to exclude string keys with specific tags from download, you should update the `flutter_intl` section of the `pubspec.yaml` file with the `download_include_tags` and `download_exclude_tags`.

```
flutter_intl:
  enabled: true
  localizely:
    project_id: <PROJECT_ID>
    download_include_tags:
      - SignUp
      - Settings
      - Home Page
      - Gallery
    download_exclude_tags:
      - EmailTemplates
```

To pass include/exclude tags during the command run, you can use the `download-include-tags` and `download-exclude-tags` optional args.

```
flutter pub run intl_utils:localizely_download --download-include-tags=SignUp,Settings,"Home Page",Gallery --download-exclude-tags=EmailTemplates
```

**All config is optional.*
**Passing optional args during command run will overwrite configuration from the `pubspec.yaml` file.*
