### ISSUE TITLE
Analyzer version is old

### ISSUE THREAD

**Issue by AAkira** [localizely/intl_utils#60]
I use this library and [freezed](https://pub.dev/packages/freezed).

Please update the [analyzer](https://pub.dev/packages/analyzer) version.

https://github.com/localizely/intl_utils/blob/master/pubspec.yaml#L10

```
Because freezed 0.14.5 depends on analyzer ^2.0.0 and intl_utils >=2.0.0 depends on analyzer ^1.0.0, freezed 0.14.5 is incompatible with intl_utils >=2.0.0.
```

**Comment by aleksakrstic** [comment]
Hi @AAkira 
Thanks for reporting this!
We will consider that for the next version release.

**Comment by tomwyr** [comment]
Is there a new version planned anytime soon?

**Comment by aleksakrstic** [comment]
Probably in around 3-4 weeks

**Comment by jangruenwaldt** [comment]
You can also just fork and adjust easily in the meantime...

**Comment by luis901101** [comment]
Hi. I just made a [PR 61](https://github.com/localizely/intl_utils/pull/61) with the analyzer dependency updated as well as the rest of the dependencies:
In the mean time you can use:

```yaml
intl_utils: #^2.4.0
    git:
      url: https://github.com/luis901101/intl_utils.git
      ref: depedencies_update
```

**Comment by danielgomezrico** [comment]
Im getting the same, my dependencies:

```YAML
dev_dependencies:
  build_runner: 2.1.2
  chopper_generator: 4.0.2
  built_value_generator: 8.1.2
  intl_utils: 2.4.0
```

Error:
```dart
Because built_value_generator >=8.1.2 depends on analyzer >=1.8.0 <3.0.0 and no versions of analyzer match ^1.8.0, built_value_generator >=8.1.2 requires analyzer ^2.0.0.
And because intl_utils >=2.0.0 depends on analyzer ^1.0.0, intl_utils >=2.0.0 is incompatible with built_value_generator >=8.1.2.
So, because client depends on both built_value_generator 8.1.2 and intl_utils 2.4.0, version solving failed.
pub get failed (1; So, because client depends on both built_value_generator 8.1.2 and intl_utils 2.4.0, version solving failed.)
```
