### ISSUE TITLE
Unable to resolve package "intl_utils" with the given git parameters.

### ISSUE THREAD

**Issue by Wolfteam** [localizely/intl_utils#79]
Hiho, I've been using the following github action without any problems:

```
name: flutter_tests
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set flutter version
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.2'
          
      - name: Generate localization files
        run: |
          flutter pub add intl_utils
          flutter pub run intl_utils:generate

      - name: Restore packages
        run: flutter pub get
          
      - name: Run build_runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --coverage
```

but 1 week ago, the `flutter pub add intl_utils` fails with the following msg:

![image](https://user-images.githubusercontent.com/1976115/161887654-e806c5f2-2ee6-4c52-b5c7-d0f451822fda.png)

Not sure what has changed to make the github action fail :C

**Comment by lzoran** [comment]
Hi @Wolfteam,

Not sure what might be the problem. The latest release of the `intl_utils` package was ~2 months ago ([changelog](https://pub.dev/packages/intl_utils/changelog)).

Could you check your `pubspec.yaml` file? The message (_"Unable to resolve package "intl_utils" **with the given git parameter**s"_) and exit code (65) indicate that the problem might be there.

**Comment by Wolfteam** [comment]
Indeed you were right, it seems flutter (or github) changed the way you pass the url to point to a github repo, 

I had:
```
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
```

and had to change it to:
```
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
```
