### ISSUE TITLE
Feature request: Possibility to add ignore coverage comments to generated files

### ISSUE THREAD

**Issue by fideldonson** [localizely/intl_utils#94]
In order to exclude generated files from coverage when running tests it would be usefull to be able to add `// coverage:ignore-file` to the generated files.
This could be setup in the pubspec.yaml file for the project:
```
flutter_intl:
    main_locale: da_DK
    enabled: true
    ignore_coverage: true
```
